#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Insufficent number of parameters supplied. Please enter 2 parameters."
	exit 1
fi

ls -1 | grep -q *$1
if [ $? -ne 0  ]; then
	echo "No file exists with the $1 file extension"
	exit 1
fi

for file in *$1; do
	[ -f "$file" ] && mv "$file" "${file/$1/$2}" || echo "An error occured for $(file)"
done

